export const GET_REQRES_USERS_ATTEMPT = 'GET_REQRES_USERS_ATTEMPT';
export const GET_REQRES_USERS_SUCCESS = 'GET_REQRES_USERS_SUCCESS';
export const GET_REQRES_USERS_FAILURE = 'GET_REQRES_USERS_FAILURE';

export const GET_REQRES_RESOURCE_ATTEMPT = 'GET_REQRES_RESOURCE_ATTEMPT';
export const GET_REQRES_RESOURCE_SUCCESS = 'GET_REQRES_RESOURCE_SUCCESS';
export const GET_REQRES_RESOURCE_FAILURE = 'GET_REQRES_RESOURCE_FAILURE';
